-- Enable necessary extensions if needed (though not strictly required for this schema)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create barangays table
CREATE TABLE IF NOT EXISTS barangays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    municipality TEXT NOT NULL,
    barangay_name TEXT NOT NULL,
    puroks INTEGER DEFAULT 0,
    pk_teams INTEGER DEFAULT 0,
    pk_team_members INTEGER DEFAULT 0,
    pk_kits_received INTEGER DEFAULT 0,
    pk_members_oriented INTEGER DEFAULT 0,
    program1_target INTEGER DEFAULT 0,
    program2_name TEXT,
    program2_target INTEGER DEFAULT 0,
    program3_name TEXT,
    program3_target INTEGER DEFAULT 0,
    program4_name TEXT,
    program4_target INTEGER DEFAULT 0,
    actual_population INTEGER DEFAULT 0,
    projected_population INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create patients table
CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    municipality TEXT NOT NULL,
    barangay TEXT DEFAULT '',
    birthdate DATE NOT NULL,
    sex TEXT NOT NULL,
    date_of_service DATE NOT NULL,
    health_promotion BOOLEAN DEFAULT false,
    fpe BOOLEAN DEFAULT false,
    philhealth BOOLEAN DEFAULT false,
    referral BOOLEAN DEFAULT false,
    nutrition BOOLEAN DEFAULT false,
    cancer BOOLEAN DEFAULT false,
    immunization BOOLEAN DEFAULT false,
    hpn BOOLEAN DEFAULT false,
    dm BOOLEAN DEFAULT false,
    maternal_health BOOLEAN DEFAULT false,
    road_safety BOOLEAN DEFAULT false,
    mental_health BOOLEAN DEFAULT false,
    tb BOOLEAN DEFAULT false,
    hiv BOOLEAN DEFAULT false,
    wash BOOLEAN DEFAULT false,
    large_scale_pk_activity BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_patients_municipality ON patients(municipality);
CREATE INDEX IF NOT EXISTS idx_patients_barangay ON patients(barangay);
CREATE INDEX IF NOT EXISTS idx_patients_date_of_service ON patients(date_of_service);
CREATE INDEX IF NOT EXISTS idx_patients_full_name ON patients(full_name);
CREATE INDEX IF NOT EXISTS idx_patients_birthdate ON patients(birthdate);
CREATE INDEX IF NOT EXISTS idx_patients_sex ON patients(sex);

-- Composite index for duplicate check
CREATE INDEX IF NOT EXISTS idx_patients_duplicate_check ON patients(full_name, birthdate, municipality);

-- Enable Row Level Security (RLS)
ALTER TABLE barangays ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;

-- Drop existings policies to ensure rerun safety (idempotency)
DROP POLICY IF EXISTS "Allow public read access to barangays" ON barangays;
DROP POLICY IF EXISTS "Allow public insert access to barangays" ON barangays;
DROP POLICY IF EXISTS "Allow public update access to barangays" ON barangays;
DROP POLICY IF EXISTS "Allow public delete access to barangays" ON barangays;

DROP POLICY IF EXISTS "Allow public read access to patients" ON patients;
DROP POLICY IF EXISTS "Allow public insert access to patients" ON patients;
DROP POLICY IF EXISTS "Allow public update access to patients" ON patients;
DROP POLICY IF EXISTS "Allow public delete access to patients" ON patients;

-- Create policies to allow public access (since we are using anon key for now)
-- In a production app with auth, you would restrict this further.
CREATE POLICY "Allow public read access to barangays" ON barangays FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to barangays" ON barangays FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to barangays" ON barangays FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access to barangays" ON barangays FOR DELETE USING (true);

CREATE POLICY "Allow public read access to patients" ON patients FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to patients" ON patients FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to patients" ON patients FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access to patients" ON patients FOR DELETE USING (true);

-- Create patient_services table for history
CREATE TABLE IF NOT EXISTS patient_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
    date_of_service DATE NOT NULL,
    health_promotion BOOLEAN DEFAULT false,
    fpe BOOLEAN DEFAULT false,
    philhealth BOOLEAN DEFAULT false,
    referral BOOLEAN DEFAULT false,
    nutrition BOOLEAN DEFAULT false,
    cancer BOOLEAN DEFAULT false,
    immunization BOOLEAN DEFAULT false,
    hpn BOOLEAN DEFAULT false,
    dm BOOLEAN DEFAULT false,
    maternal_health BOOLEAN DEFAULT false,
    road_safety BOOLEAN DEFAULT false,
    mental_health BOOLEAN DEFAULT false,
    tb BOOLEAN DEFAULT false,
    hiv BOOLEAN DEFAULT false,
    wash BOOLEAN DEFAULT false,
    large_scale_pk_activity BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on patient_services
ALTER TABLE patient_services ENABLE ROW LEVEL SECURITY;

-- Drop existing patient_services policies
DROP POLICY IF EXISTS "Allow public read access to patient_services" ON patient_services;
DROP POLICY IF EXISTS "Allow public insert access to patient_services" ON patient_services;
DROP POLICY IF EXISTS "Allow public update access to patient_services" ON patient_services;
DROP POLICY IF EXISTS "Allow public delete access to patient_services" ON patient_services;

-- Create policies for patient_services
CREATE POLICY "Allow public read access to patient_services" ON patient_services FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to patient_services" ON patient_services FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access to patient_services" ON patient_services FOR UPDATE USING (true);
CREATE POLICY "Allow public delete access to patient_services" ON patient_services FOR DELETE USING (true);

-- Create audit_logs table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    username TEXT NOT NULL,
    role TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing audit_logs policies
DROP POLICY IF EXISTS "Allow public read access to audit_logs" ON audit_logs;
DROP POLICY IF EXISTS "Allow public insert access to audit_logs" ON audit_logs;

CREATE POLICY "Allow public read access to audit_logs" ON audit_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert access to audit_logs" ON audit_logs FOR INSERT WITH CHECK (true);

-- Indexes for patient_services performance
CREATE INDEX IF NOT EXISTS idx_patient_services_patient_id ON patient_services(patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_services_date_of_service ON patient_services(date_of_service);

-- High-performance composite indexes for joins and aggregation
CREATE INDEX IF NOT EXISTS idx_patients_location_id_optimized ON patients (LOWER(municipality), LOWER(barangay), id);
CREATE INDEX IF NOT EXISTS idx_patient_services_perf_date_patient ON patient_services (date_of_service, patient_id);
CREATE INDEX IF NOT EXISTS idx_patient_services_perf_patient_date ON patient_services (patient_id, date_of_service);

-- High-performance optimized function for dashboard stats
DROP FUNCTION IF EXISTS public.get_dashboard_service_stats(text, text, date, date);
CREATE OR REPLACE FUNCTION public.get_dashboard_service_stats(
    p_municipality text DEFAULT NULL,
    p_barangay text DEFAULT NULL,
    p_start_date date DEFAULT NULL,
    p_end_date date DEFAULT NULL
)
RETURNS json
SECURITY DEFINER
AS $$
DECLARE
    v_result json;
    v_sql text;
BEGIN
    v_sql := $query$
    WITH patient_first_services AS (
        SELECT 
            ps.patient_id,
            LOWER(p.municipality) as lmuni,
            LOWER(p.barangay) as lbrgy,
            MIN(CASE WHEN ps.nutrition THEN ps.date_of_service END) as first_nutrition_date,
            MIN(CASE WHEN ps.cancer THEN ps.date_of_service END) as first_cancer_date,
            MIN(CASE WHEN ps.immunization THEN ps.date_of_service END) as first_immunization_date,
            MIN(CASE WHEN ps.hpn THEN ps.date_of_service END) as first_hpn_date,
            MIN(CASE WHEN ps.dm THEN ps.date_of_service END) as first_dm_date,
            MIN(CASE WHEN ps.maternal_health THEN ps.date_of_service END) as first_maternal_health_date,
            MIN(CASE WHEN ps.road_safety THEN ps.date_of_service END) as first_road_safety_date,
            MIN(CASE WHEN ps.mental_health THEN ps.date_of_service END) as first_mental_health_date,
            MIN(CASE WHEN ps.tb THEN ps.date_of_service END) as first_tb_date,
            MIN(CASE WHEN ps.hiv THEN ps.date_of_service END) as first_hiv_date,
            MIN(CASE WHEN ps.wash THEN ps.date_of_service END) as first_wash_date,
            MIN(CASE WHEN ps.health_promotion THEN ps.date_of_service END) as first_health_promotion_date,
            MIN(CASE WHEN ps.fpe THEN ps.date_of_service END) as first_fpe_date,
            MIN(CASE WHEN ps.philhealth THEN ps.date_of_service END) as first_philhealth_date,
            MIN(CASE WHEN ps.referral THEN ps.date_of_service END) as first_referral_date,
            MIN(CASE WHEN ps.large_scale_pk_activity THEN ps.date_of_service END) as first_large_scale_pk_activity_date,
            MIN(ps.date_of_service) as absolute_first_service_date
        FROM patient_services ps
        JOIN patients p ON ps.patient_id = p.id
        WHERE 1=1 $query$;

    IF p_municipality IS NOT NULL THEN
        v_sql := v_sql || $query$ AND LOWER(p.municipality) = LOWER($1) $query$;
    END IF;

    IF p_barangay IS NOT NULL THEN
        v_sql := v_sql || $query$ AND LOWER(p.barangay) = LOWER($2) $query$;
    END IF;

    v_sql := v_sql || $query$
        GROUP BY ps.patient_id, LOWER(p.municipality), LOWER(p.barangay)
    ),
    patient_period_summary AS (
        SELECT 
            patient_id,
            lmuni,
            lbrgy,
            CASE WHEN ($3::date IS NULL OR first_nutrition_date >= $3::date) AND ($4::date IS NULL OR first_nutrition_date <= $4::date) THEN first_nutrition_date ELSE NULL END as first_nutrition_date,
            CASE WHEN ($3::date IS NULL OR first_cancer_date >= $3::date) AND ($4::date IS NULL OR first_cancer_date <= $4::date) THEN first_cancer_date ELSE NULL END as first_cancer_date,
            CASE WHEN ($3::date IS NULL OR first_immunization_date >= $3::date) AND ($4::date IS NULL OR first_immunization_date <= $4::date) THEN first_immunization_date ELSE NULL END as first_immunization_date,
            CASE WHEN ($3::date IS NULL OR first_hpn_date >= $3::date) AND ($4::date IS NULL OR first_hpn_date <= $4::date) THEN first_hpn_date ELSE NULL END as first_hpn_date,
            CASE WHEN ($3::date IS NULL OR first_dm_date >= $3::date) AND ($4::date IS NULL OR first_dm_date <= $4::date) THEN first_dm_date ELSE NULL END as first_dm_date,
            CASE WHEN ($3::date IS NULL OR first_maternal_health_date >= $3::date) AND ($4::date IS NULL OR first_maternal_health_date <= $4::date) THEN first_maternal_health_date ELSE NULL END as first_maternal_health_date,
            CASE WHEN ($3::date IS NULL OR first_road_safety_date >= $3::date) AND ($4::date IS NULL OR first_road_safety_date <= $4::date) THEN first_road_safety_date ELSE NULL END as first_road_safety_date,
            CASE WHEN ($3::date IS NULL OR first_mental_health_date >= $3::date) AND ($4::date IS NULL OR first_mental_health_date <= $4::date) THEN first_mental_health_date ELSE NULL END as first_mental_health_date,
            CASE WHEN ($3::date IS NULL OR first_tb_date >= $3::date) AND ($4::date IS NULL OR first_tb_date <= $4::date) THEN first_tb_date ELSE NULL END as first_tb_date,
            CASE WHEN ($3::date IS NULL OR first_hiv_date >= $3::date) AND ($4::date IS NULL OR first_hiv_date <= $4::date) THEN first_hiv_date ELSE NULL END as first_hiv_date,
            (first_nutrition_date IS NOT NULL AND ($3::date IS NULL OR first_nutrition_date >= $3::date) AND ($4::date IS NULL OR first_nutrition_date <= $4::date)) as nutrition,
            (first_cancer_date IS NOT NULL AND ($3::date IS NULL OR first_cancer_date >= $3::date) AND ($4::date IS NULL OR first_cancer_date <= $4::date)) as cancer,
            (first_immunization_date IS NOT NULL AND ($3::date IS NULL OR first_immunization_date >= $3::date) AND ($4::date IS NULL OR first_immunization_date <= $4::date)) as immunization,
            (first_hpn_date IS NOT NULL AND ($3::date IS NULL OR first_hpn_date >= $3::date) AND ($4::date IS NULL OR first_hpn_date <= $4::date)) as hpn,
            (first_dm_date IS NOT NULL AND ($3::date IS NULL OR first_dm_date >= $3::date) AND ($4::date IS NULL OR first_dm_date <= $4::date)) as dm,
            (first_maternal_health_date IS NOT NULL AND ($3::date IS NULL OR first_maternal_health_date >= $3::date) AND ($4::date IS NULL OR first_maternal_health_date <= $4::date)) as maternal_health,
            (first_road_safety_date IS NOT NULL AND ($3::date IS NULL OR first_road_safety_date >= $3::date) AND ($4::date IS NULL OR first_road_safety_date <= $4::date)) as road_safety,
            (first_mental_health_date IS NOT NULL AND ($3::date IS NULL OR first_mental_health_date >= $3::date) AND ($4::date IS NULL OR first_mental_health_date <= $4::date)) as mental_health,
            (first_tb_date IS NOT NULL AND ($3::date IS NULL OR first_tb_date >= $3::date) AND ($4::date IS NULL OR first_tb_date <= $4::date)) as tb,
            (first_hiv_date IS NOT NULL AND ($3::date IS NULL OR first_hiv_date >= $3::date) AND ($4::date IS NULL OR first_hiv_date <= $4::date)) as hiv,
            (first_wash_date IS NOT NULL AND ($3::date IS NULL OR first_wash_date >= $3::date) AND ($4::date IS NULL OR first_wash_date <= $4::date)) as wash,
            (first_health_promotion_date IS NOT NULL AND ($3::date IS NULL OR first_health_promotion_date >= $3::date) AND ($4::date IS NULL OR first_health_promotion_date <= $4::date)) as health_promotion,
            (first_fpe_date IS NOT NULL AND ($3::date IS NULL OR first_fpe_date >= $3::date) AND ($4::date IS NULL OR first_fpe_date <= $4::date)) as fpe,
            (first_philhealth_date IS NOT NULL AND ($3::date IS NULL OR first_philhealth_date >= $3::date) AND ($4::date IS NULL OR first_philhealth_date <= $4::date)) as philhealth,
            (first_referral_date IS NOT NULL AND ($3::date IS NULL OR first_referral_date >= $3::date) AND ($4::date IS NULL OR first_referral_date <= $4::date)) as referral,
            (first_large_scale_pk_activity_date IS NOT NULL AND ($3::date IS NULL OR first_large_scale_pk_activity_date >= $3::date) AND ($4::date IS NULL OR first_large_scale_pk_activity_date <= $4::date)) as large_scale_pk_activity,
            (absolute_first_service_date IS NOT NULL AND ($3::date IS NULL OR absolute_first_service_date >= $3::date) AND ($4::date IS NULL OR absolute_first_service_date <= $4::date)) as is_new_patient
        FROM patient_first_services
        WHERE 
            (first_nutrition_date IS NOT NULL AND ($3::date IS NULL OR first_nutrition_date >= $3::date) AND ($4::date IS NULL OR first_nutrition_date <= $4::date)) OR
            (first_cancer_date IS NOT NULL AND ($3::date IS NULL OR first_cancer_date >= $3::date) AND ($4::date IS NULL OR first_cancer_date <= $4::date)) OR
            (first_immunization_date IS NOT NULL AND ($3::date IS NULL OR first_immunization_date >= $3::date) AND ($4::date IS NULL OR first_immunization_date <= $4::date)) OR
            (first_hpn_date IS NOT NULL AND ($3::date IS NULL OR first_hpn_date >= $3::date) AND ($4::date IS NULL OR first_hpn_date <= $4::date)) OR
            (first_dm_date IS NOT NULL AND ($3::date IS NULL OR first_dm_date >= $3::date) AND ($4::date IS NULL OR first_dm_date <= $4::date)) OR
            (first_maternal_health_date IS NOT NULL AND ($3::date IS NULL OR first_maternal_health_date >= $3::date) AND ($4::date IS NULL OR first_maternal_health_date <= $4::date)) OR
            (first_road_safety_date IS NOT NULL AND ($3::date IS NULL OR first_road_safety_date >= $3::date) AND ($4::date IS NULL OR first_road_safety_date <= $4::date)) OR
            (first_mental_health_date IS NOT NULL AND ($3::date IS NULL OR first_mental_health_date >= $3::date) AND ($4::date IS NULL OR first_mental_health_date <= $4::date)) OR
            (first_tb_date IS NOT NULL AND ($3::date IS NULL OR first_tb_date >= $3::date) AND ($4::date IS NULL OR first_tb_date <= $4::date)) OR
            (first_hiv_date IS NOT NULL AND ($3::date IS NULL OR first_hiv_date >= $3::date) AND ($4::date IS NULL OR first_hiv_date <= $4::date)) OR
            (first_wash_date IS NOT NULL AND ($3::date IS NULL OR first_wash_date >= $3::date) AND ($4::date IS NULL OR first_wash_date <= $4::date)) OR
            (first_health_promotion_date IS NOT NULL AND ($3::date IS NULL OR first_health_promotion_date >= $3::date) AND ($4::date IS NULL OR first_health_promotion_date <= $4::date)) OR
            (first_fpe_date IS NOT NULL AND ($3::date IS NULL OR first_fpe_date >= $3::date) AND ($4::date IS NULL OR first_fpe_date <= $4::date)) OR
            (first_philhealth_date IS NOT NULL AND ($3::date IS NULL OR first_philhealth_date >= $3::date) AND ($4::date IS NULL OR first_philhealth_date <= $4::date)) OR
            (first_referral_date IS NOT NULL AND ($3::date IS NULL OR first_referral_date >= $3::date) AND ($4::date IS NULL OR first_referral_date <= $4::date)) OR
            (first_large_scale_pk_activity_date IS NOT NULL AND ($3::date IS NULL OR first_large_scale_pk_activity_date >= $3::date) AND ($4::date IS NULL OR first_large_scale_pk_activity_date <= $4::date)) OR
            (absolute_first_service_date IS NOT NULL AND ($3::date IS NULL OR absolute_first_service_date >= $3::date) AND ($4::date IS NULL OR absolute_first_service_date <= $4::date))
    ),
    activity_services AS (
        SELECT 
            ps.date_of_service,
            LOWER(p.municipality) as lmuni,
            LOWER(p.barangay) as lbrgy,
            BOOL_OR(ps.large_scale_pk_activity) as has_large_scale,
            BOOL_OR(ps.large_scale_pk_activity AND ps.nutrition) as ls_nutrition,
            BOOL_OR(ps.large_scale_pk_activity AND ps.cancer) as ls_cancer,
            BOOL_OR(ps.large_scale_pk_activity AND ps.immunization) as ls_immunization,
            BOOL_OR(ps.large_scale_pk_activity AND ps.hpn) as ls_hpn,
            BOOL_OR(ps.large_scale_pk_activity AND ps.dm) as ls_dm,
            BOOL_OR(ps.large_scale_pk_activity AND ps.maternal_health) as ls_maternal_health,
            BOOL_OR(ps.large_scale_pk_activity AND ps.road_safety) as ls_road_safety,
            BOOL_OR(ps.large_scale_pk_activity AND ps.mental_health) as ls_mental_health,
            BOOL_OR(ps.large_scale_pk_activity AND ps.tb) as ls_tb,
            BOOL_OR(ps.large_scale_pk_activity AND ps.hiv) as ls_hiv,
            BOOL_OR(ps.large_scale_pk_activity AND ps.wash) as ls_wash,
            BOOL_OR(ps.large_scale_pk_activity AND ps.health_promotion) as ls_health_promotion,
            BOOL_OR(ps.large_scale_pk_activity AND ps.fpe) as ls_fpe,
            BOOL_OR(ps.large_scale_pk_activity AND ps.philhealth) as ls_philhealth,
            BOOL_OR(ps.large_scale_pk_activity AND ps.referral) as ls_referral
        FROM patient_services ps
        JOIN patients p ON ps.patient_id = p.id
        WHERE 1=1 $query$;

    IF p_municipality IS NOT NULL THEN
        v_sql := v_sql || $query$ AND LOWER(p.municipality) = LOWER($1) $query$;
    END IF;

    IF p_barangay IS NOT NULL THEN
        v_sql := v_sql || $query$ AND LOWER(p.barangay) = LOWER($2) $query$;
    END IF;

    IF p_start_date IS NOT NULL THEN
        v_sql := v_sql || $query$ AND ps.date_of_service >= $3 $query$;
    END IF;

    IF p_end_date IS NOT NULL THEN
        v_sql := v_sql || $query$ AND ps.date_of_service <= $4 $query$;
    END IF;

    v_sql := v_sql || $query$
        GROUP BY ps.date_of_service, LOWER(p.municipality), LOWER(p.barangay)
    ),
    barangay_activities AS (
        SELECT 
            lmuni,
            lbrgy,
            COUNT(*)::bigint as pk_activities,
            COUNT(CASE WHEN has_large_scale THEN 1 END)::bigint as large_scale_activities,
            COUNT(CASE WHEN ls_nutrition THEN 1 END)::bigint as ls_nutrition,
            COUNT(CASE WHEN ls_cancer THEN 1 END)::bigint as ls_cancer,
            COUNT(CASE WHEN ls_immunization THEN 1 END)::bigint as ls_immunization,
            COUNT(CASE WHEN ls_hpn THEN 1 END)::bigint as ls_hpn,
            COUNT(CASE WHEN ls_dm THEN 1 END)::bigint as ls_dm,
            COUNT(CASE WHEN ls_maternal_health THEN 1 END)::bigint as ls_maternal_health,
            COUNT(CASE WHEN ls_road_safety THEN 1 END)::bigint as ls_road_safety,
            COUNT(CASE WHEN ls_mental_health THEN 1 END)::bigint as ls_mental_health,
            COUNT(CASE WHEN ls_tb THEN 1 END)::bigint as ls_tb,
            COUNT(CASE WHEN ls_hiv THEN 1 END)::bigint as ls_hiv,
            COUNT(CASE WHEN ls_wash THEN 1 END)::bigint as ls_wash,
            COUNT(CASE WHEN ls_health_promotion THEN 1 END)::bigint as ls_health_promotion,
            COUNT(CASE WHEN ls_fpe THEN 1 END)::bigint as ls_fpe,
            COUNT(CASE WHEN ls_philhealth THEN 1 END)::bigint as ls_philhealth,
            COUNT(CASE WHEN ls_referral THEN 1 END)::bigint as ls_referral
        FROM activity_services
        GROUP BY lmuni, lbrgy
    ),
    program_stats_calc AS (
        SELECT
            SUM(CASE WHEN nutrition THEN 1 ELSE 0 END)::int as nutrition,
            SUM(CASE WHEN cancer THEN 1 ELSE 0 END)::int as cancer,
            SUM(CASE WHEN immunization THEN 1 ELSE 0 END)::int as immunization,
            SUM(CASE WHEN hpn THEN 1 ELSE 0 END)::int as hpn,
            SUM(CASE WHEN dm THEN 1 ELSE 0 END)::int as dm,
            SUM(CASE WHEN maternal_health THEN 1 ELSE 0 END)::int as maternal_health,
            SUM(CASE WHEN road_safety THEN 1 ELSE 0 END)::int as road_safety,
            SUM(CASE WHEN mental_health THEN 1 ELSE 0 END)::int as mental_health,
            SUM(CASE WHEN tb THEN 1 ELSE 0 END)::int as tb,
            SUM(CASE WHEN hiv THEN 1 ELSE 0 END)::int as hiv,
            SUM(CASE WHEN wash THEN 1 ELSE 0 END)::int as wash,
            SUM(CASE WHEN health_promotion THEN 1 ELSE 0 END)::int as health_promotion,
            SUM(CASE WHEN fpe THEN 1 ELSE 0 END)::int as fpe,
            SUM(CASE WHEN philhealth THEN 1 ELSE 0 END)::int as philhealth,
            SUM(CASE WHEN referral THEN 1 ELSE 0 END)::int as referral,
            SUM(CASE WHEN is_new_patient THEN 1 ELSE 0 END)::int as total_population_reached,
            SUM(CASE WHEN large_scale_pk_activity THEN 1 ELSE 0 END)::int as total_large_scale_clients_served,
            SUM(CASE WHEN large_scale_pk_activity AND (nutrition OR cancer OR immunization OR hpn OR dm OR maternal_health OR road_safety OR mental_health OR tb OR hiv OR wash) THEN 1 ELSE 0 END)::int as total_priority_large_scale_patients
        FROM patient_period_summary
    ),
    large_scale_details AS (
        SELECT
            COALESCE(SUM(ba.pk_activities), 0) as total_pk_activities,
            COALESCE(SUM(ba.large_scale_activities), 0) as total_large_scale_activities,
            COALESCE(SUM(ba.ls_nutrition), 0) as ls_nutrition,
            COALESCE(SUM(ba.ls_cancer), 0) as ls_cancer,
            COALESCE(SUM(ba.ls_immunization), 0) as ls_immunization,
            COALESCE(SUM(ba.ls_hpn), 0) as ls_hpn,
            COALESCE(SUM(ba.ls_dm), 0) as ls_dm,
            COALESCE(SUM(ba.ls_maternal_health), 0) as ls_maternal_health,
            COALESCE(SUM(ba.ls_road_safety), 0) as ls_road_safety,
            COALESCE(SUM(ba.ls_mental_health), 0) as ls_mental_health,
            COALESCE(SUM(ba.ls_tb), 0) as ls_tb,
            COALESCE(SUM(ba.ls_hiv), 0) as ls_hiv,
            COALESCE(SUM(ba.ls_wash), 0) as ls_wash,
            COALESCE(SUM(ba.ls_health_promotion), 0) as ls_health_promotion,
            COALESCE(SUM(ba.ls_fpe), 0) as ls_fpe,
            COALESCE(SUM(ba.ls_philhealth), 0) as ls_philhealth,
            COALESCE(SUM(ba.ls_referral), 0) as ls_referral
        FROM barangay_activities ba
    ),
    muni_stats AS (
        SELECT
            lmuni as muni,
            (
                SUM(CASE WHEN nutrition THEN 1 ELSE 0 END) +
                SUM(CASE WHEN cancer THEN 1 ELSE 0 END) +
                SUM(CASE WHEN immunization THEN 1 ELSE 0 END) +
                SUM(CASE WHEN hpn THEN 1 ELSE 0 END) +
                SUM(CASE WHEN dm THEN 1 ELSE 0 END) +
                SUM(CASE WHEN maternal_health THEN 1 ELSE 0 END) +
                SUM(CASE WHEN road_safety THEN 1 ELSE 0 END) +
                SUM(CASE WHEN mental_health THEN 1 ELSE 0 END) +
                SUM(CASE WHEN tb THEN 1 ELSE 0 END) +
                SUM(CASE WHEN hiv THEN 1 ELSE 0 END)
            )::int as served,
            SUM(CASE WHEN wash THEN 1 ELSE 0 END)::int as households_served,
            SUM(CASE WHEN is_new_patient THEN 1 ELSE 0 END)::int as population_reached
        FROM patient_period_summary
        GROUP BY lmuni
    ),
    barangay_stats AS (
        SELECT
            ps.lmuni as muni,
            ps.lbrgy as brgy,
            (
                SUM(CASE WHEN ps.nutrition THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.cancer THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.immunization THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.hpn THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.dm THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.maternal_health THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.road_safety THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.mental_health THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.tb THEN 1 ELSE 0 END) +
                SUM(CASE WHEN ps.hiv THEN 1 ELSE 0 END)
            )::int as served,
            SUM(CASE WHEN ps.wash THEN 1 ELSE 0 END)::int as households_served,
            SUM(CASE WHEN ps.nutrition THEN 1 ELSE 0 END)::int as nutrition_served,
            SUM(CASE WHEN ps.cancer THEN 1 ELSE 0 END)::int as cancer_served,
            SUM(CASE WHEN ps.immunization THEN 1 ELSE 0 END)::int as immunization_served,
            SUM(CASE WHEN ps.hpn THEN 1 ELSE 0 END)::int as hpn_served,
            SUM(CASE WHEN ps.dm THEN 1 ELSE 0 END)::int as dm_served,
            SUM(CASE WHEN ps.maternal_health THEN 1 ELSE 0 END)::int as maternal_health_served,
            SUM(CASE WHEN ps.road_safety THEN 1 ELSE 0 END)::int as road_safety_served,
            SUM(CASE WHEN ps.mental_health THEN 1 ELSE 0 END)::int as mental_health_served,
            SUM(CASE WHEN ps.tb THEN 1 ELSE 0 END)::int as tb_served,
            SUM(CASE WHEN ps.hiv THEN 1 ELSE 0 END)::int as hiv_served,
            SUM(CASE WHEN ps.wash THEN 1 ELSE 0 END)::int as wash_served,
            SUM(CASE WHEN ps.health_promotion THEN 1 ELSE 0 END)::int as health_promotion_served,
            SUM(CASE WHEN ps.fpe THEN 1 ELSE 0 END)::int as fpe_served,
            SUM(CASE WHEN ps.philhealth THEN 1 ELSE 0 END)::int as philhealth_served,
            SUM(CASE WHEN ps.referral THEN 1 ELSE 0 END)::int as referral_served,
            
            COALESCE(MAX(ba.pk_activities), 0) as pk_activities,
            COALESCE(MAX(ba.large_scale_activities), 0) as large_scale_activities,
            COALESCE(MAX(ba.ls_nutrition), 0) as ls_nutrition,
            COALESCE(MAX(ba.ls_cancer), 0) as ls_cancer,
            COALESCE(MAX(ba.ls_immunization), 0) as ls_immunization,
            COALESCE(MAX(ba.ls_hpn), 0) as ls_hpn,
            COALESCE(MAX(ba.ls_dm), 0) as ls_dm,
            COALESCE(MAX(ba.ls_maternal_health), 0) as ls_maternal_health,
            COALESCE(MAX(ba.ls_road_safety), 0) as ls_road_safety,
            COALESCE(MAX(ba.ls_mental_health), 0) as ls_mental_health,
            COALESCE(MAX(ba.ls_tb), 0) as ls_tb,
            COALESCE(MAX(ba.ls_hiv), 0) as ls_hiv,
            COALESCE(MAX(ba.ls_wash), 0) as ls_wash,
            COALESCE(MAX(ba.ls_health_promotion), 0) as ls_health_promotion,
            COALESCE(MAX(ba.ls_fpe), 0) as ls_fpe,
            COALESCE(MAX(ba.ls_philhealth), 0) as ls_philhealth,
            COALESCE(MAX(ba.ls_referral), 0) as ls_referral,
            SUM(CASE WHEN ps.large_scale_pk_activity THEN 1 ELSE 0 END)::int as total_large_scale_clients_served,
            SUM(CASE WHEN ps.large_scale_pk_activity AND (ps.nutrition OR ps.cancer OR ps.immunization OR ps.hpn OR ps.dm OR ps.maternal_health OR ps.road_safety OR ps.mental_health OR ps.tb OR ps.hiv OR ps.wash) THEN 1 ELSE 0 END)::int as total_priority_large_scale_patients
        FROM patient_period_summary ps
        LEFT JOIN barangay_activities ba ON ps.lmuni = ba.lmuni AND ps.lbrgy = ba.lbrgy
        GROUP BY ps.lmuni, ps.lbrgy
    ),
    first_service_dates_flat AS (
        SELECT
            fd.fd
        FROM patient_period_summary fsd,
        LATERAL (
            VALUES 
                (fsd.first_nutrition_date),
                (fsd.first_cancer_date),
                (fsd.first_immunization_date),
                (fsd.first_hpn_date),
                (fsd.first_dm_date),
                (fsd.first_maternal_health_date),
                (fsd.first_road_safety_date),
                (fsd.first_mental_health_date),
                (fsd.first_tb_date),
                (fsd.first_hiv_date)
        ) as fd(fd)
        WHERE fd.fd IS NOT NULL
    ),
    monthly_trends AS (
        SELECT
            DATE_TRUNC('month', fd)::date as month_date,
            TRIM(TO_CHAR(fd, 'Month')) as month_name,
            COALESCE(COUNT(*)::int, 0) as served
        FROM first_service_dates_flat
        GROUP BY 1, 2
        ORDER BY month_date ASC
    )
    SELECT json_build_object(
        'programStats', (
            SELECT json_build_object(
                'total_served', (nutrition + cancer + immunization + hpn + dm + maternal_health + road_safety + mental_health + tb + hiv),
                'total_population_reached', total_population_reached,
                'health_promotion', health_promotion,
                'fpe', fpe,
                'philhealth', philhealth,
                'referral', referral,
                'nutrition', nutrition,
                'cancer', cancer,
                'immunization', immunization,
                'hpn', hpn,
                'dm', dm,
                'maternal_health', maternal_health,
                'road_safety', road_safety,
                'mental_health', mental_health,
                'tb', tb,
                'hiv', hiv,
                'wash', wash
            ) FROM program_stats_calc
        ),
        'largeScaleStats', (
            SELECT json_build_object(
                'total_pk_activities', total_pk_activities,
                'total_large_scale_activities', total_large_scale_activities,
                'total_large_scale_clients_served', (SELECT total_large_scale_clients_served FROM program_stats_calc),
                'total_priority_large_scale_patients', (SELECT total_priority_large_scale_patients FROM program_stats_calc),
                'ls_nutrition', ls_nutrition,
                'ls_cancer', ls_cancer,
                'ls_immunization', ls_immunization,
                'ls_hpn', ls_hpn,
                'ls_dm', ls_dm,
                'ls_maternal_health', ls_maternal_health,
                'ls_road_safety', ls_road_safety,
                'ls_mental_health', ls_mental_health,
                'ls_tb', ls_tb,
                'ls_hiv', ls_hiv,
                'ls_wash', ls_wash,
                'ls_health_promotion', ls_health_promotion,
                'ls_fpe', ls_fpe,
                'ls_philhealth', ls_philhealth,
                'ls_referral', ls_referral
            ) FROM large_scale_details
        ),
        'muniStats', COALESCE((
            SELECT json_agg(json_build_object(
                'muni', muni,
                'served', served,
                'households_served', households_served,
                'population_reached', population_reached
            )) FROM muni_stats
        ), '[]'::json),
        'barangayStats', COALESCE((
            SELECT json_agg(json_build_object(
                'muni', muni,
                'brgy', brgy,
                'served', served,
                'households_served', households_served,
                'nutrition_served', nutrition_served,
                'cancer_served', cancer_served,
                'immunization_served', immunization_served,
                'hpn_served', hpn_served,
                'dm_served', dm_served,
                'maternal_health_served', maternal_health_served,
                'road_safety_served', road_safety_served,
                'mental_health_served', mental_health_served,
                'tb_served', tb_served,
                'hiv_served', hiv_served,
                'wash_served', wash_served,
                'health_promotion_served', health_promotion_served,
                'fpe_served', fpe_served,
                'philhealth_served', philhealth_served,
                'referral_served', referral_served,
                'pk_activities', pk_activities,
                'large_scale_activities', large_scale_activities,
                'ls_nutrition', ls_nutrition,
                'ls_cancer', ls_cancer,
                'ls_immunization', ls_immunization,
                'ls_hpn', ls_hpn,
                'ls_dm', ls_dm,
                'ls_maternal_health', ls_maternal_health,
                'ls_road_safety', ls_road_safety,
                'ls_mental_health', ls_mental_health,
                'ls_tb', ls_tb,
                'ls_hiv', ls_hiv,
                'ls_wash', ls_wash,
                'ls_health_promotion', ls_health_promotion,
                'ls_fpe', ls_fpe,
                'ls_philhealth', ls_philhealth,
                'ls_referral', ls_referral,
                'total_large_scale_clients_served', total_large_scale_clients_served,
                'total_priority_large_scale_patients', total_priority_large_scale_patients
            )) FROM barangay_stats
        ), '[]'::json),
        'monthlyTrends', COALESCE((
            SELECT json_agg(json_build_object(
                'month_date', month_date,
                'month_name', month_name,
                'served', served
            )) FROM monthly_trends
        ), '[]'::json)
    )$query$;

    EXECUTE v_sql INTO v_result USING p_municipality, p_barangay, p_start_date, p_end_date;

    RETURN v_result;
END;
$$ LANGUAGE plpgsql SET statement_timeout = '120s';

-- Create the summary table
CREATE TABLE IF NOT EXISTS dashboard_summary (
    id SERIAL PRIMARY KEY,
    municipality TEXT NOT NULL,
    barangay TEXT NOT NULL,
    total_patients INT DEFAULT 0,
    total_services INT DEFAULT 0,
    nutrition INT DEFAULT 0,
    cancer INT DEFAULT 0,
    immunization INT DEFAULT 0,
    hpn INT DEFAULT 0,
    dm INT DEFAULT 0,
    maternal_health INT DEFAULT 0,
    road_safety INT DEFAULT 0,
    mental_health INT DEFAULT 0,
    tb INT DEFAULT 0,
    hiv INT DEFAULT 0,
    wash INT DEFAULT 0,
    health_promotion INT DEFAULT 0,
    fpe INT DEFAULT 0,
    philhealth INT DEFAULT 0,
    referral INT DEFAULT 0,
    large_scale_pk_activity INT DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(municipality, barangay)
);

CREATE POLICY "Allow public read access to dashboard_summary" ON dashboard_summary FOR SELECT USING (true);
CREATE POLICY "Allow public all access to dashboard_summary" ON dashboard_summary FOR ALL USING (true);
ALTER TABLE dashboard_summary ENABLE ROW LEVEL SECURITY;

-- Create trigger function
CREATE OR REPLACE FUNCTION update_dashboard_summary_func()
RETURNS TRIGGER AS $$
DECLARE
    v_municipality TEXT;
    v_barangay TEXT;
BEGIN
    IF TG_TABLE_NAME = 'patients' THEN
        IF TG_OP = 'INSERT' THEN
            INSERT INTO dashboard_summary (municipality, barangay, total_patients)
            VALUES (NEW.municipality, NEW.barangay, 1)
            ON CONFLICT (municipality, barangay) DO UPDATE
            SET total_patients = dashboard_summary.total_patients + 1, last_updated = NOW();
        ELSIF TG_OP = 'DELETE' THEN
            UPDATE dashboard_summary SET total_patients = GREATEST(0, total_patients - 1), last_updated = NOW()
            WHERE municipality = OLD.municipality AND barangay = OLD.barangay;
        END IF;
        RETURN NULL;
    ELSIF TG_TABLE_NAME = 'patient_services' THEN
        -- we need patient info to get municipality and barangay
        IF TG_OP = 'INSERT' THEN
            SELECT municipality, barangay INTO v_municipality, v_barangay FROM patients WHERE id = NEW.patient_id;
            
            INSERT INTO dashboard_summary (
                municipality, barangay, total_services,
                nutrition, cancer, immunization, hpn, dm, maternal_health,
                road_safety, mental_health, tb, hiv, wash, health_promotion,
                fpe, philhealth, referral, large_scale_pk_activity
            ) VALUES (
                v_municipality, v_barangay, 1,
                CASE WHEN NEW.nutrition THEN 1 ELSE 0 END,
                CASE WHEN NEW.cancer THEN 1 ELSE 0 END,
                CASE WHEN NEW.immunization THEN 1 ELSE 0 END,
                CASE WHEN NEW.hpn THEN 1 ELSE 0 END,
                CASE WHEN NEW.dm THEN 1 ELSE 0 END,
                CASE WHEN NEW.maternal_health THEN 1 ELSE 0 END,
                CASE WHEN NEW.road_safety THEN 1 ELSE 0 END,
                CASE WHEN NEW.mental_health THEN 1 ELSE 0 END,
                CASE WHEN NEW.tb THEN 1 ELSE 0 END,
                CASE WHEN NEW.hiv THEN 1 ELSE 0 END,
                CASE WHEN NEW.wash THEN 1 ELSE 0 END,
                CASE WHEN NEW.health_promotion THEN 1 ELSE 0 END,
                CASE WHEN NEW.fpe THEN 1 ELSE 0 END,
                CASE WHEN NEW.philhealth THEN 1 ELSE 0 END,
                CASE WHEN NEW.referral THEN 1 ELSE 0 END,
                CASE WHEN NEW.large_scale_pk_activity THEN 1 ELSE 0 END
            )
            ON CONFLICT (municipality, barangay) DO UPDATE
            SET 
                total_services = dashboard_summary.total_services + 1,
                nutrition = dashboard_summary.nutrition + CASE WHEN NEW.nutrition THEN 1 ELSE 0 END,
                cancer = dashboard_summary.cancer + CASE WHEN NEW.cancer THEN 1 ELSE 0 END,
                immunization = dashboard_summary.immunization + CASE WHEN NEW.immunization THEN 1 ELSE 0 END,
                hpn = dashboard_summary.hpn + CASE WHEN NEW.hpn THEN 1 ELSE 0 END,
                dm = dashboard_summary.dm + CASE WHEN NEW.dm THEN 1 ELSE 0 END,
                maternal_health = dashboard_summary.maternal_health + CASE WHEN NEW.maternal_health THEN 1 ELSE 0 END,
                road_safety = dashboard_summary.road_safety + CASE WHEN NEW.road_safety THEN 1 ELSE 0 END,
                mental_health = dashboard_summary.mental_health + CASE WHEN NEW.mental_health THEN 1 ELSE 0 END,
                tb = dashboard_summary.tb + CASE WHEN NEW.tb THEN 1 ELSE 0 END,
                hiv = dashboard_summary.hiv + CASE WHEN NEW.hiv THEN 1 ELSE 0 END,
                wash = dashboard_summary.wash + CASE WHEN NEW.wash THEN 1 ELSE 0 END,
                health_promotion = dashboard_summary.health_promotion + CASE WHEN NEW.health_promotion THEN 1 ELSE 0 END,
                fpe = dashboard_summary.fpe + CASE WHEN NEW.fpe THEN 1 ELSE 0 END,
                philhealth = dashboard_summary.philhealth + CASE WHEN NEW.philhealth THEN 1 ELSE 0 END,
                referral = dashboard_summary.referral + CASE WHEN NEW.referral THEN 1 ELSE 0 END,
                large_scale_pk_activity = dashboard_summary.large_scale_pk_activity + CASE WHEN NEW.large_scale_pk_activity THEN 1 ELSE 0 END,
                last_updated = NOW();
        ELSIF TG_OP = 'DELETE' THEN
            SELECT municipality, barangay INTO v_municipality, v_barangay FROM patients WHERE id = OLD.patient_id;
            
            UPDATE dashboard_summary SET
                total_services = GREATEST(0, total_services - 1),
                nutrition = GREATEST(0, nutrition - CASE WHEN OLD.nutrition THEN 1 ELSE 0 END),
                cancer = GREATEST(0, cancer - CASE WHEN OLD.cancer THEN 1 ELSE 0 END),
                immunization = GREATEST(0, immunization - CASE WHEN OLD.immunization THEN 1 ELSE 0 END),
                hpn = GREATEST(0, hpn - CASE WHEN OLD.hpn THEN 1 ELSE 0 END),
                dm = GREATEST(0, dm - CASE WHEN OLD.dm THEN 1 ELSE 0 END),
                maternal_health = GREATEST(0, maternal_health - CASE WHEN OLD.maternal_health THEN 1 ELSE 0 END),
                road_safety = GREATEST(0, road_safety - CASE WHEN OLD.road_safety THEN 1 ELSE 0 END),
                mental_health = GREATEST(0, mental_health - CASE WHEN OLD.mental_health THEN 1 ELSE 0 END),
                tb = GREATEST(0, tb - CASE WHEN OLD.tb THEN 1 ELSE 0 END),
                hiv = GREATEST(0, hiv - CASE WHEN OLD.hiv THEN 1 ELSE 0 END),
                wash = GREATEST(0, wash - CASE WHEN OLD.wash THEN 1 ELSE 0 END),
                health_promotion = GREATEST(0, health_promotion - CASE WHEN OLD.health_promotion THEN 1 ELSE 0 END),
                fpe = GREATEST(0, fpe - CASE WHEN OLD.fpe THEN 1 ELSE 0 END),
                philhealth = GREATEST(0, philhealth - CASE WHEN OLD.philhealth THEN 1 ELSE 0 END),
                referral = GREATEST(0, referral - CASE WHEN OLD.referral THEN 1 ELSE 0 END),
                large_scale_pk_activity = GREATEST(0, large_scale_pk_activity - CASE WHEN OLD.large_scale_pk_activity THEN 1 ELSE 0 END),
                last_updated = NOW()
            WHERE municipality = v_municipality AND barangay = v_barangay;
        END IF;
        RETURN NULL;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Drop existing triggers to avoid duplication
DROP TRIGGER IF EXISTS dashboard_summary_patient_trigger ON patients;
DROP TRIGGER IF EXISTS dashboard_summary_service_trigger ON patient_services;

-- Create triggers
CREATE TRIGGER dashboard_summary_patient_trigger
AFTER INSERT OR DELETE ON patients
FOR EACH ROW EXECUTE FUNCTION update_dashboard_summary_func();

CREATE TRIGGER dashboard_summary_service_trigger
AFTER INSERT OR DELETE ON patient_services
FOR EACH ROW EXECUTE FUNCTION update_dashboard_summary_func();

-- Initial Population Script
INSERT INTO dashboard_summary (
    municipality, barangay, total_services,
    nutrition, cancer, immunization, hpn, dm, maternal_health, road_safety,
    mental_health, tb, hiv, wash, health_promotion, fpe, philhealth, referral, large_scale_pk_activity
)
SELECT
    LOWER(p.municipality), LOWER(p.barangay),
    COUNT(ps.id) as total_services,
    COUNT(CASE WHEN ps.nutrition THEN 1 END) as nutrition,
    COUNT(CASE WHEN ps.cancer THEN 1 END) as cancer,
    COUNT(CASE WHEN ps.immunization THEN 1 END) as immunization,
    COUNT(CASE WHEN ps.hpn THEN 1 END) as hpn,
    COUNT(CASE WHEN ps.dm THEN 1 END) as dm,
    COUNT(CASE WHEN ps.maternal_health THEN 1 END) as maternal_health,
    COUNT(CASE WHEN ps.road_safety THEN 1 END) as road_safety,
    COUNT(CASE WHEN ps.mental_health THEN 1 END) as mental_health,
    COUNT(CASE WHEN ps.tb THEN 1 END) as tb,
    COUNT(CASE WHEN ps.hiv THEN 1 END) as hiv,
    COUNT(CASE WHEN ps.wash THEN 1 END) as wash,
    COUNT(CASE WHEN ps.health_promotion THEN 1 END) as health_promotion,
    COUNT(CASE WHEN ps.fpe THEN 1 END) as fpe,
    COUNT(CASE WHEN ps.philhealth THEN 1 END) as philhealth,
    COUNT(CASE WHEN ps.referral THEN 1 END) as referral,
    COUNT(CASE WHEN ps.large_scale_pk_activity THEN 1 END) as large_scale_pk_activity
FROM patient_services ps
JOIN patients p ON ps.patient_id = p.id
GROUP BY LOWER(p.municipality), LOWER(p.barangay)
ON CONFLICT (municipality, barangay) DO UPDATE
SET 
    total_services = EXCLUDED.total_services,
    nutrition = EXCLUDED.nutrition,
    cancer = EXCLUDED.cancer,
    immunization = EXCLUDED.immunization,
    hpn = EXCLUDED.hpn,
    dm = EXCLUDED.dm,
    maternal_health = EXCLUDED.maternal_health,
    road_safety = EXCLUDED.road_safety,
    mental_health = EXCLUDED.mental_health,
    tb = EXCLUDED.tb,
    hiv = EXCLUDED.hiv,
    wash = EXCLUDED.wash,
    health_promotion = EXCLUDED.health_promotion,
    fpe = EXCLUDED.fpe,
    philhealth = EXCLUDED.philhealth,
    referral = EXCLUDED.referral,
    large_scale_pk_activity = EXCLUDED.large_scale_pk_activity,
    last_updated = NOW();

WITH patient_counts AS (
    SELECT LOWER(municipality) as municipality, LOWER(barangay) as barangay, COUNT(id) as total_patients
    FROM patients
    GROUP BY LOWER(municipality), LOWER(barangay)
)
UPDATE dashboard_summary ds
SET total_patients = pc.total_patients
FROM patient_counts pc
WHERE ds.municipality = pc.municipality AND ds.barangay = pc.barangay; 

